# Generated by Django 5.1.4 on 2024-12-28 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_alter_cartechchar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartechchar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='car_milage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(600000)], verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='power',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='vin',
            field=models.IntegerField(unique=True, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Год'),
        ),
    ]
