# Generated by Django 5.1.4 on 2024-12-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_alter_cartechchar_brand_alter_cartechchar_car_milage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name_model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='cartechchar',
            name='vin',
            field=models.CharField(max_length=17, unique=True, verbose_name='VIN'),
        ),
    ]
