# Generated by Django 5.1.4 on 2024-12-28 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0004_alter_carbrand_name_alter_carmodel_name_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartechchar',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartechchar',
            name='date_update',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
